//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET
    {
        public string tenlaisuat { get; set; }
        public string tenngoaite { get; set; }
        public string sosotk { get; set; }
        public string magiaodich { get; set; }
        public DateTime ngaygiaodich { get; set; }
        public string malaisuat { get; set; }
        public string mangoaite { get; set; }
        public Nullable<double> sotiengiaodich { get; set; }
        public Nullable<double> tongtiensaulai { get; set; }
        public DateTime hanrut { get; set; }
    
        public virtual LAISUAT LAISUAT { get; set; }
        public virtual NGOAITE NGOAITE { get; set; }
        public virtual SOTIETKIEM SOTIETKIEM { get; set; }
    }
}
